index:
    path: /proveedor
    controller: App\Controller\ProveedorController::index

proveedor_create:
    path: /proveedor/create
    controller: App\Controller\ProveedorController::nuevoProveedor


